In [1]:
import tensorflow as tf
import numpy as np

In [12]:
a = tf.constant([[3.]])
W = tf.constant(np.ones((4,1)))
#b = tf.matmul(W,a)
sess = tf.InteractiveSession()
#sess.run(b)

Exception AssertionError: AssertionError() in <bound method InteractiveSession.__del__ of <tensorflow.python.client.session.InteractiveSession object at 0x1126f0fd0>> ignored


In [6]:
np.ones((4,1))

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [23]:
a = tf.placeholder(tf.float32, [1, 1])
b = tf.placeholder(tf.float32, [4, 1])
bias = tf.placeholder(tf.float32, [4])
c = b * a #+ bias
c = tf.reshape(c, [1,4])
c = c + bias
sess.run(c, feed_dict={a: [[2.]], b: np.ones((4,1)), bias: np.ones((4))})

array([[ 3.,  3.,  3.,  3.]], dtype=float32)

In [18]:
np.ones((4))  

array([ 1.,  1.,  1.,  1.])

In [54]:
a = tf.placeholder(tf.float32, [2,3])
b = tf.placeholder(tf.float32, [2,3])
output = [a,b]
c = tf.concat(1, output)
d = tf.reshape(c, [-1, 3])
sess.run(d, feed_dict ={a:np.zeros((2,3)), b:np.ones((2,3))})

array([[ 0.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 0.,  0.,  0.],
       [ 1.,  1.,  1.]], dtype=float32)

In [30]:
a  = np.ones((1,4))
print(a[:,1])

[ 1.]


In [31]:
np.ones(1)

array([ 1.])

In [36]:
print("fefe %f", a[0][0])

('fefe %f', 1.0)


In [39]:
output = []
batch_size = 3
word_vec_size = 4
a = np.ones([batch_size, word_vec_size])
output.append(a)
b = np.ones([batch_size, word_vec_size])
output.append(b)
c = np.ones([batch_size, word_vec_size])
output.append(c)

In [43]:
np.concat(1, output)

AttributeError: 'module' object has no attribute 'concat'

In [57]:
a = np.zeros((1,2))
a[0][0] = 1
a

array([[ 1.,  0.]])

In [58]:
np.argmax(a)

0

In [63]:
a = [1,2,3,4]
a = np.asarray(a).reshape(1,4)

In [65]:
34 / 4.0

8.5